version: '3.2'

services:
  db:
    name: mariadb
    hostname: db
    image: mariadb
    tag: 10.4.4-bionic
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb_admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud_admin
      - MYSQL_PASSWORD=nextcloud_admin
  fpm:
    name: fpm
    hostname: fpm 
    image: 1john2ci/nextcloud
    tag: 16.0-fpm-full
    restart: always
    volumes:
      - nextcloud:/var/www/html
  app:
    name: nextcloud
    hostname: nextcloud
    image: 1john2ci/nextcloud
    tag: 16.0-nginx
    restart: always
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud_admin
      - MYSQL_PASSWORD=nextcloud_admin
      - MYSQL_HOST=db
    depends_on:
      - db
      - fpm
  cron:
    image: nextcloud
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db

volumes:
  db: /srv/mariadb
  nextcloud: /srv/nextcloud
